.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH EVENTSTAT 8 "June 13, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
eventstat \- a tool to measure system events.
.br

.SH SYNOPSIS
.B eventstat
.RI [options] " [delay " [count]]
.br

.SH DESCRIPTION
eventstat is a program that dumps the current active system events. 

.SH OPTIONS
eventstat options are as follow:
.TP
.B \-h
show help
.TP
.B \-n event_count
only display the first event_count number of top events.
.TP
.B \-q 
run quietly, only really makes sense with \-r option.
.TP
.B \-r csv_file
output gathered data in a comma separated values file. This
can be then imported and graphed using your favourite open
source spread sheet.
.TP
.B \-s
report short process name from /proc/pid/cmdline in CSV output. This reports
just the process name.
.TP
.B \-l
report long process name from /proc/pid/cmdline in CSV output. This reports
the process name and all the command line arguments.
.TP
.B \-d
strip full directory path off the process name in the CSV output.
.TP
.B \-t threshold
ignore samples where the event delta per second less than the given threshold.
.TP
.B \-c
report cumulative events rather than events per sample period.
.SH EXAMPLES
.LP
Dump events every second until stopped.
.RS 8
sudo eventstat
.RE
.LP
Dump the top 20 events every 60 seconds until stopped.
.RS 8
sudo eventstat \-n 20 60
.RE
.LP
Dump events every 10 seconds just 5 times.
.RS 8
sudo eventstat 10 5
.RE
.LP
Quietly dump events every 10 seconds just 5 times into a CSV file with short process name.
.RS 8
sudo eventstat 10 5 \-q \-s \-r results.csv
.RE
.SH SEE ALSO
.BR powertop (8) 
.SH AUTHOR
eventstat was written by Colin King <colin.king@canonical.com>
.PP
This manual page was written by Colin King <colin.king@canonical.com>,
for the Ubuntu project (but may be used by others).
