name: eventstat
version: 0.03.3-20161115-254-9585650
summary: kernel event states monitoring tool
description:  Eventstat periodically dumps out the current kernel event state.  It keeps track of current events and outputs the change in events on each output update.  The tool requires sudo to run since it needs to write to /proc/timer_stats to start and stop the event monitoring.

confinement: strict

parts:
    eventstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/eventstat
        build-packages:
            - gcc
            - make

apps:
    eventstat:
        command: usr/bin/eventstat

