name: eventstat
summary: kernel event states monitoring tool
description:  Eventstat periodically dumps out the current kernel event state.  It keeps track of current events and outputs the change in events on each output update.  The tool requires sudo to run since it needs to write to /proc/timer_stats to start and stop the event monitoring.
confinement: strict
type: app
grade: stable
assumes: [snapd2.45]
base: core20
adopt-info: eventstat

architectures:
    - build-on: s390x
    - build-on: ppc64el
    - build-on: arm64
    - build-on: armhf
    - build-on: amd64
    - build-on: i386

parts:
    eventstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/eventstat
        override-pull: |
            snapcraftctl pull
            description="$(git describe HEAD --tags)"
            sha=$(echo $description | tr '-' ' ' | awk '{print $NF}')
            version=${description%$sha}
            commits=$(git log --oneline | wc -l)
            date=$(date +'%Y%m%d')
            if test "$description" = "$sha"
            then
                version="$description"
            else
                version=$(echo $version$date-$commits-$sha | cut -c1-32)
            fi
            snapcraftctl set-version "$version"
        build-packages:
            - gcc
            - make
            - libncurses5-dev

apps:
    eventstat:
        command: usr/bin/eventstat

