name: eventstat
version: git
version-script: |
    echo $(git describe --tags)
summary: kernel event states monitoring tool
description:  Eventstat periodically dumps out the current kernel event state.  It keeps track of current events and outputs the change in events on each output update.  The tool requires sudo to run since it needs to write to /proc/timer_stats to start and stop the event monitoring.
confinement: strict
type: app
grade: stable

parts:
    eventstat:
        plugin: make
        source: git://kernel.ubuntu.com/cking/eventstat
        build-packages:
            - gcc
            - make
            - libncurses5-dev

apps:
    eventstat:
        command: usr/bin/eventstat

